project_id = "praotzblwslmmlyhodya"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.phone-login]
verify_jwt = false

[functions.send-to-telegram]
verify_jwt = false
