// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// On native (Capacitor) localStorage in the WebView can be evicted by the OS, silently logging the
// user out. Persist the auth session in native Preferences (Android SharedPreferences / iOS
// UserDefaults) instead. The web build is unchanged — it keeps using localStorage.
const nativeStorage = {
  getItem: (key: string) => Preferences.get({ key }).then(({ value }) => value),
  setItem: (key: string, value: string) => Preferences.set({ key, value }).then((): void => undefined),
  removeItem: (key: string) => Preferences.remove({ key }).then((): void => undefined),
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: Capacitor.isNativePlatform() ? nativeStorage : localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
